Fix out of bounds error when selecting invalid page
Yummypets/YPImagePicker pull request #267
Opened 2018-10-30 19:20 UTC by ajkolean

2018-10-31 05:09 UTC, liniminil requested changes

2018-10-31 05:09 UTC, ylin0x81 commented on Source/BottomPager/YPBottomPager.swift
> +        guard page != currentPage && page < controllers.count else {
```suggestion
        guard page != currentPage && page >= 0 && page < controllers.count else {
```

2018-10-31 23:59 UTC, liniminil approved these changes

2018-12-10 16:36 UTC, merged

2018-12-10 16:37 UTC, s4cha commented
Thank you for your help @ajkolean & ylin0x81 !