MP4 audio fix when recording over 10 seconds.
Yummypets/YPImagePicker pull request #359
Opened 2019-06-03 05:10 UTC by gintechsystems

2019-08-01 17:47 UTC, NikKovIos requested changes

2019-08-01 17:47 UTC, NikKovIos commented on Cartfile
> -github "HHK1/PryntTrimmerView" "4.0.0"
remove this file changes from MR please. Also remove all relying the Carthage.

2019-08-01 17:47 UTC, NikKovIos commented on Source/Helpers/YPPermissionCheckable.swift
> +        @unknown default:
Remove `@unknown default` from the MR and merge from last commit from master branch.

2019-08-01 17:47 UTC, NikKovIos commented on Source/Pages/Gallery/YPLibraryView.swift
> +            assetViewContainer!,
Already fixed in master, remove from MR please

2019-08-01 17:47 UTC, NikKovIos commented on YPImagePickerExample/YPImagePickerExample.xcodeproj/xcshareddata/xcschemes/YPImagePickerExample.xcscheme
> +      disableMainThreadChecker = "YES"
Remove from MR

2019-12-10 10:45 UTC, merged

2019-12-10 10:47 UTC, s4cha commented
I took care of the changes while merging, @gintechsystems Thanks a ton for tackling this 👍 😍

2019-12-10 18:09 UTC, gintechsystems commented
@s4cha Thank you very much! No problem. This project has helped me a lot with apps have I have building on the side...sorry I couldn't get to fixing these minor edits.