Support preselected items
Yummypets/YPImagePicker pull request #370
Opened 2019-07-16 14:32 UTC by kf99916

The feature lets users can select/deselect items back and forth.

2019-08-01 17:43 UTC, NikKovIos requested changes

2019-08-01 17:43 UTC, NikKovIos commented on YPImagePickerExample/YPImagePickerExample/ExampleViewController.swift
> +        let picker = YPImagePicker(configuration: config, items: selectedItems)
Sorry, but this is a major update for API. Please use YPConfigLibrary to put this configuration into.

2019-08-01 17:43 UTC, NikKovIos commented on Source/YPPickerVC.swift
> +            libraryVC = YPLibraryVC(items: preSelectedItems)
There and in other place, not need to camel case for `preselected`.

2019-08-01 17:43 UTC, NikKovIos commented on Source/Pages/Gallery/YPLibraryVC+CollectionView.swift
> +            let currentSelection = selection[index]
Please add a comment in code what is happening there.

2019-08-20 07:33 UTC, kf99916 commented
@NikKovIos , the PR is refined according to your suggestion. Thanks you.

2019-08-20 22:59 UTC, NikKovIos commented
@kf99916 Mark as resolved appropriate conversations

2019-09-12 10:59 UTC, touyu commented
When will this be merged? I want this feature.

2019-09-17 08:40 UTC, merged