Hides cancel button on demand
Yummypets/YPImagePicker pull request #394
Opened 2019-09-16 15:31 UTC by pepsin

2019-10-12 20:02 UTC, NikKovIos requested changes

2019-10-12 20:02 UTC, NikKovIos commented on Source/Configuration/YPImagePickerConfiguration.swift
> +	public var hidesCancelButton = false
Fix the indentation.

2019-10-12 20:02 UTC, NikKovIos commented on Source/Helpers/Extensions/PHCachingImageManager+Extensions.swift
> +import UIKit.UIImage
Not necessary change. Remove it.

2019-10-12 20:02 UTC, NikKovIos commented on Source/YPPickerVC.swift
> +		}
Fix the indentation.

2019-10-12 20:02 UTC, NikKovIos commented on Source/Helpers/YPPhotoSaver.swift
> +import UIKit.UIImage
Not necessary change. Remove.

2019-12-11 13:10 UTC, s4cha commented
@pepsin Congrats for your first contribution! I guess this is for the case where you want the user to select a picture mo matter what and prevent it from going back. Looks like a valid use case to me :)

2019-12-11 13:23 UTC, s4cha commented
Could you please fix the conflicts ?

2020-08-05 07:57 UTC, s4cha commented
I just added your request, lots of things happened in between which made it hard to merge so I directly updated master with your changes.

2020-08-05 07:57 UTC, closed without merging