If onlySquare is enabled, execute fitImage on display.
Yummypets/YPImagePicker pull request #777
Opened 2022-12-15 12:44 UTC by hanawat

#776 

To fix above issue.

If `onlySquare` is enabled when displaying an Asset, call `fitImage` to crop it to a square.

You can see how it works in the sample apps in the `feature/demo` branch.
https://github.com/hanawat/YPImagePicker/tree/feature/demo

| Before  | After |
| ------- | ----- |
| <img width="300" alt="スクリーンショット 2022-12-15 21 33 07" src="https://user-images.githubusercontent.com/11912668/207861823-2e163102-a011-4130-bb0f-73b3cae8a41e.png"> | <img width="300" alt="スクリーンショット 2022-12-15 21 33 21" src="https://user-images.githubusercontent.com/11912668/207861863-67203b40-f0e1-4c30-8194-cfdf8d64b393.png">  |

2023-01-29 00:02 UTC, keremcesme approved these changes
I have tested. It runs smoothly for videos.

It works for video but. The change code also needs to be put inside the `setImage()` function. You made this change only for the `setVideo()` function.

`

    public func setImage() {
             // HERE                             
            if YPConfig.library.onlySquare {
                strongSelf.fitImage(true)
            }
            
            completion(isLowResIntermediaryImage)
        }
    }
`

2023-01-29 00:26 UTC, keremcesme requested changes
The same code needs to be added for `setImage()` function as well.

2023-02-15 22:07 UTC, ramboli1986 commented
With this fix, the selected image view can't be moved up when scrolling. Can you take a look?

2023-02-17 07:15 UTC, hanawat commented
@keremcesme Thank you for your review. Videos in the library also used `fitImage`.

2023-02-17 07:18 UTC, hanawat commented
@ramboli1986 Did you run that in the sample app? I checked and it works fine in the sample app.

2023-02-21 15:20 UTC, ramboli1986 commented
> @ramboli1986 Did you run that in the sample app? I checked and it works fine in the sample app.

No I was on latest master banch.

2023-02-22 01:21 UTC, ramboli1986 commented
> @ramboli1986 Did you run that in the sample app? I checked and it works fine in the sample app.

Nvm, I can't repo it any more.

2023-06-07 09:23 UTC, rance-attack commented on Source/Pages/Gallery/YPAssetZoomableView.swift
> +            }
I think we can replace it with
```
strongSelf.fitImage(YPConfig.library.onlySquare || YPConfig.library.isSquareByDefault)
```
squaredZoomScale is calculated in fitImage()

2025-06-26 14:28 UTC, NikKovIos commented
PR is very outdated. Thanks for your collaboration. Feel free to open 🙏🏻

2025-06-26 14:28 UTC, closed without merging