Allow to customize the list of filters using the configuration object
Yummypets/YPImagePicker pull request #89
Opened 2018-04-15 20:27 UTC by heitara

Expose a new class YPFilterDescriptor which can be used to add new filters to the collection of predefined ones. The demo project is updated as well. In future, the descriptor class may be extended to allow fine tuning of each filter.

2018-04-16 09:54 UTC, s4cha commented
Wow!
the fact that we can customize filters like : 
```swift
config.filters = [
    YPFilterDescriptor(name: "Blur" , filterName: "CIBoxBlur"),
    YPFilterDescriptor(name: "Normal", filterName: ""),
    YPFilterDescriptor(name: "Mono", filterName: "CIPhotoEffectMono"),
    YPFilterDescriptor(name: "Sepia", filterName: "CISepiaTone")
]
```
is really neat! 

We'll wait to know what are @NikKovIos thoughts, but I really like it!

Great job man! 👏

2018-04-16 13:58 UTC, NikKovIos commented
The feature is great! However, I saw a code and it really needs swiflint.

There are few things to do before merge:
1) Fix syntax. For example fix `let name:String` to `let name: String`
`filterName: String )` to  `filterName: String)` and so on.
2) Bring the default filters into the YPFiltersVC.swift. It's not necessary to set them in config due to most of people, i think, wouldn't customize them. So if filters:[YPFilterDescriptor] var in configuration would be nil, use the default filters. 
3) Fix  config.showsFilters = !false and leave only necessary example code. For ex: ` config.showsFilters = false`. `config.filters.remove(at: 1)` `config.filters.insert(YPFilterDescriptor(name: "Blur" , filterName: "CIBoxBlur"), at: 1)`

 After that we can merge it.

2018-04-16 13:58 UTC, NikKovIos requested changes
The feature is great! However, I saw a code and it really needs swiflint.

There are few things to do before merge:
1) Fix syntax. For example fix `let name:String` to `let name: String`
`filterName: String )` to  `filterName: String)` and so on.
2) Bring the default filters into the YPFiltersVC.swift. It's not necessary to set them in config due to most of people, i think, wouldn't customize them. So if filters:[YPFilterDescriptor] var in configuration would be nil, use the default filters. 
3) Fix  config.showsFilters = !false and leave only necessary example code. For ex: ` config.showsFilters = false`. `config.filters.remove(at: 1)` `config.filters.insert(YPFilterDescriptor(name: "Blur" , filterName: "CIBoxBlur"), at: 1)`

 After that we can merge it.

2018-04-18 09:48 UTC, merged

2018-04-18 10:49 UTC, heitara commented
Thanks!